demo_blog:
    resource: "@DemoBlogBundle/Resources/config/routing.yml"
    prefix:   /

demo_blog_homepage:
    pattern:   /hello/{name}
    defaults:  {_controller: DemoBlogBundle:Default:index}    

DemoBlogBundle_post:
    resource: "@DemoBlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"