post:
    path:     /
    defaults: { _controller: "DemoBlogBundle:Post:index" }

post_show:
    path:     /{id}/show
    defaults: { _controller: "DemoBlogBundle:Post:show" }

post_new:
    path:     /new
    defaults: { _controller: "DemoBlogBundle:Post:new" }

post_create:
    path:     /create
    defaults: { _controller: "DemoBlogBundle:Post:create" }
    requirements: { _method: post }

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "DemoBlogBundle:Post:edit" }

post_update:
    path:     /{id}/update
    defaults: { _controller: "DemoBlogBundle:Post:update" }
    requirements: { _method: post|put }

post_delete:
    path:     /{id}/delete
    defaults: { _controller: "DemoBlogBundle:Post:delete" }
    requirements: { _method: post|delete }
